version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
    - location: scripts/node_install.sh
      timeout: 300
      runas: root
    - location: scripts/httpd_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/next_build.sh
      timeout: 300
      runas: root
    - location: scripts/start_next.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/httpd_stop.sh
      timeout: 300
      runas: root
