version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Packaging the application...
      - zip -r source-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip .
      - echo Uploading the package to S3...
      - aws s3 cp source-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip s3://my-app-bucket/source/
      - echo Cleaning up...
      - rm source-${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip

artifacts:
  files:
    - '**/*'
  base-directory: '.next'
