import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/app/context/ReduxToolkitProvider";

export const metadata: Metadata = {
  title: "Mental Calculation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
